### ISSUE TITLE
Speed up BFG Bitcoin Block Processing

### ISSUE THREAD

**Issue by max-sanchez** [hemilabs/heminetwork#11]
### Confirmation

- [X] I have checked for similar issues.

### Problem

BFG processes Bitcoin blocks by requesting a single transaction at a time from Electrumx, which causes block processing to take too long when the latency between BFG and Electrumx is too high. 

### Suggested solution

Need to update BFG block processing to parallelize BTC tx queries to Elecrumx.

**Comment by joshuasing** [comment]
Additionally, the current electrumx client does not persist TCP connections. Each request results in a new TCP connection being established, a request/response being made and the connection being closed.

**Comment by joshuasing** [comment]
I believe this was resolved by #26, however we may replace ElectrumX with TBC in BFG at a later date to further resolve this issue.
