### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by iCapt** [hemilabs/heminetwork#208]
### Confirmation

- [X] I have checked for similar issues.

### Problem

Category : UI/UX Add Light and Dark Feature
Category : UI/UX  Add wallet disconnect feature
Category UI/UX : Add Profile Feature

### Suggested solution

Category : UI/UX Add Light and Dark feature
So that users can choose their own comfort level when accessing the web later, light and dark Fiture should be added
Category : UI/UX  Add wallet disconnect feature  
Add Diconnect Wallet Fiture and When you click on disconnect button, it shouldn't just disconnect that way(instantly), there should be an option to really confirm from the user if he really wants to disconnect just in case the user mistakenly clicked on the disconnect button.
Category UI/UX : Add Profile feature
It may be necessary to add a profile feature where users have the right to upload photos of themselves on the profile and of course it is necessary to add a text box containing their own description later

**Comment by joshuasing** [comment]
Hi @iCapt, thanks for the suggestions.
We have many sites and components, which are you suggesting these for? Thanks

**Comment by jcvernaleo** [comment]
Closing since this isn't the correct repository.  Feel free to open in other ones.
