### ISSUE TITLE
a typo in bssd

### ISSUE THREAD

**Issue by NorthernWinter** [hemilabs/heminetwork#260]
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

when run bssd with default value there is double // in URL
ws://localhost:8080//v1/ws/private
<img width="597" alt="image" src="https://github.com/user-attachments/assets/c484feb5-e315-4d8c-b7d0-9af8316e8dae">

### Expected behaviour

ws://localhost:8080/v1/ws/private
only 1 /

### Environment

Version: 
Operating System: 
Architecture:

**Comment by joshuasing** [comment]
Thank you for reporting this! I have created a pull request to resolve this.
https://github.com/hemilabs/heminetwork/pull/262
