### ISSUE TITLE
When using the self-host bfgd,How do I need to set up op-geth-l1?

### ISSUE THREAD

**Issue by lk0pa** [hemilabs/heminetwork#281]
I changed the bitcoin node to testnet, should I change the op-geth-l1 setting from dev to sepolia?
![Image](https://github.com/user-attachments/assets/71893b08-8491-4cae-92a0-a2abf55bdd51)

**Comment by ClaytonNorthey92** [comment]
hey @lk0pa I apologize for the delayed response.  yes; if you're going to use btc testnet, you'll need to use sepolia as well 👍 .  our pop txs mined in btc testnet are rolled up to sepolia
