### ISSUE TITLE
[Bug] - Cannot join Discord Server

### ISSUE THREAD

**Issue by ffrediani** [hemilabs/heminetwork#319]
### Confirmation

- [x] I have checked for similar issues.

### Describe the bug

Since Discord is the only way to get in touch and that is problem I came to report here.
I am unable to join Hemi's Discord Server. Every time I try to enter on https://discord.com/invite/hemixyz it get kicked straight away without showing any reason for that. Since I was never able to join I don't thin that was done manually.

What may be happening that may be preventing me to join. Any particular profile setting I need and is not clear before joining ?

Alternatively can you provide an email address to get in touch ?

### Expected behaviour

To be able to join Hemi's Discord Server

**Comment by jcvernaleo** [comment]
This is not related to the hemi network code.

**Comment by ffrediani** [comment]
@jcvernaleo so you don't really care much about the fact the nobody thought about not having another method of support other than something that is used for gaming and which is not working as expected ?

**Comment by jcvernaleo** [comment]
We have a number of other methods of contact including most of the common social networks and email.

Yes discord was primarily a gaming chat platform, but it is very common in this industry.

This repo in particular is for the hemi network code.  Anything outside of that is off topic.

As for the discord not working as expected, we have a number of anti spam features in place which can prevent certain accounts from joining.  Account age is one.  Another is that you must have a fully setup account (as in no default icon).  You can try some things like that and reach out on a more appropriate platform where like email if you need additional help.

**Comment by ffrediani** [comment]
Right. I have been searching for the email method but can't find anywhere.

Would you be able to at least point me that and that will help to resolve it ?

My Discord account is older so must not be that. Should be the icon maybe. I will try.
In any way let me know the email address so I can use in the future if needed.

Thanks

**Comment by jcvernaleo** [comment]
https://docs.hemi.xyz/send-feedback/contact-us

**Comment by ffrediani** [comment]
Thanks for that.
Changing the default Discord avatar worked.
Noted the email for future needs.
