### ISSUE TITLE
Fatal: Error starting protocol stack: open /tmp/jwt/jwt.hex: is a directory

### ISSUE THREAD

**Issue by NorthernWinter** [hemilabs/heminetwork#321]
### Confirmation

- [x] I have checked for similar issues.

### Describe the bug

I‘m trying to deploy local hemi node(https://github.com/hemilabs/heminetwork/blob/main/localnode/NODE_RUNNING.md) and got this error message

**Fatal: Error starting protocol stack: open /tmp/jwt/jwt.hex: is a directory**

and jwt.txt was created as a folder as attached
![Image](https://github.com/user-attachments/assets/5bb28f6f-1a21-488a-8652-058d1319ca25)
Please help to fix.

### Expected behaviour

jwt.txt to be created as a file, but not a folder

### Environment

Version: 
Operating System: 
Architecture:

**Comment by ClaytonNorthey92** [comment]
this one is on me, taking a look now.  I think it's because we mix up file names (i.e. `jwt.hex` and `jwt.txt`) when mounting, so if docker can't find the file when mounting it creates an empty directory, thus causing the issue.  

working on a fix now

**Comment by ClaytonNorthey92** [comment]
hey @NorthernWinter , could you pull the latest and try again? I believe this was due to docker creating an empty directory for a file it did not find (I recently committed a fix in #331 )

**Comment by NorthernWinter** [comment]
Hi @ClaytonNorthey92 I think this was fixed, now I can see logs as below
I'll leave it running and will see if it'll finally works or not.
![Image](https://github.com/user-attachments/assets/be829770-798c-442b-8ffb-1a9b92630187)
Thank you for your quick help.

**Comment by ClaytonNorthey92** [comment]
awesome @NorthernWinter , let us know (via opening another issue) if you're having more problems 👍 thanks!
