### ISSUE TITLE
Error Management

### ISSUE THREAD

**Issue by 2000kazim** [hemilabs/heminetwork#348]
### Confirmation

- [x] I have checked for similar issues.

### Problem

https://github.com/hemilabs/heminetwork/blob/main/ethereum/ethereum.go

There is no error handling in the code. 

### Suggested solution

I think error handling is important in cryptography and key manipulation. For example, appropriate error messages can be added for invalid keys or bad data.

**Comment by joshuasing** [comment]
The referenced code does not have error management as nothing used by the functions can return an error to manage, nor can most of the code fail in a way that would produce an error.

Validation errors are handled in other parts of the codebase.
