### ISSUE TITLE
Implement "retry" when mining L2 Keystones in PoP Miner

### ISSUE THREAD

**Issue by ClaytonNorthey92** [hemilabs/heminetwork#7]
### Confirmation

- [X] I have checked for similar issues.

### Problem

As of right now, if pop miner fails to mine a keystone, it won't retry.  It's possible a one-off error occurs in this moment and a retry would succeed.

### Suggested solution

Implement some sort of retry for pop miner when "mining keystones".  This will require some discussion; the retry strategy, limit, etc. all need to be discussed.

### Additional Information

as of writing this, this refers to the `mineKeystone` function in `popm.go`

**Comment by ClaytonNorthey92** [comment]
some thoughts:
* we should make this check for the L2 Keystone already existing in the btc chain before mining, that way we (for the most part) don't waste btc on redundant mining

**Comment by ClaytonNorthey92** [comment]
talking to @max-sanchez , we're going to do this:
* have a circular buffer of 10 keystones
* when we get a new keystone, push to that buffer, overriding the oldest when it's full
* up either new keystone, or a timer (we'll start with every 100ms)
  * iterate through the keystones, oldest first, then try to mine each one if not "successfully mined"
  * upon success mark keystone "successfully mined"

**Comment by max-sanchez** [comment]
@ClaytonNorthey92 One tweak - we should iterate through newest keystone first.

Also 100ms seems aggressive, maybe 15 seconds or something?

**Comment by ClaytonNorthey92** [comment]
@max-sanchez 

> One tweak - we should iterate through newest keystone first.
got it, can do 👍 

> Also 100ms seems aggressive, maybe 15 seconds or something?
yeah that works 👍
